# NumPy 完整知识点学习笔记

此笔记涵盖 NumPy 的主要功能、常用方法及示例代码，便于快速入门和复习。

## 1. 创建数组
- `np.array()`
- `np.arange()`
- `np.linspace()`
- `np.zeros()`、`np.ones()`、`np.eye()`
- 随机数组：`np.random.rand()`、`np.random.randint()`

In [67]:
# 示例
import numpy as np, pandas as pd

a = np.array([1, 2, 3])
b = np.arange(0, 10, 2) # 区间 [0, 10)
c = np.linspace(0, 1, 5) #闭区间
d = np.zeros((2, 3))
e = np.ones(4)
f = np.eye(3)
g = np.random.rand(2, 2)
h = np.random.randint(0, 10, size=(3,)) # 区间 [0, 10)

a, b, c, d, e, f, g, h

(array([1, 2, 3]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([1., 1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0.73059547, 0.57596964],
        [0.40493453, 0.94371525]]),
 array([9, 9, 4]))

## 2. 数组属性
- `ndim`：维度
- `shape`：形状
- `size`：元素个数
- `dtype`：数据类型

In [58]:
# 示例
arr = np.random.rand(3, 4)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)

ndim: 2
shape: (3, 4)
size: 12
dtype: float64


## 3. 索引与切片
- 基本索引
- 切片 `start:stop:step`
- 多维索引

In [61]:
# 示例
arr = np.arange(10) # default 从 0 开始
print(arr)
print(arr[0], arr[-1])
print(arr[2:7:2])

mat = np.arange(12).reshape(3, 4)
print(mat)
print(mat[1, 2])
print(mat[0:2, 1:3])

[0 1 2 3 4 5 6 7 8 9]
0 9
[2 4 6]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[[1 2]
 [5 6]]


## 4. 布尔索引
根据条件筛选数组元素。

In [62]:
# 示例
arr = np.arange(10)
mask = arr % 2 == 0  # 偶数
print(mask)
print(arr[mask])
print(arr[arr > 5])

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[6 7 8 9]


## 5. 算术运算与通用函数
- 加减乘除
- `np.add`、`np.subtract`、`np.multiply`、`np.divide`
- 三角函数、指数、对数等

In [63]:
# 示例
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("加:", a + b)
print("乘:", a * b)
print("sin:", np.sin(a))
print("exp:", np.exp(a))
print("log:", np.log(b))

加: [5 7 9]
乘: [ 4 10 18]
sin: [0.84147098 0.90929743 0.14112001]
exp: [ 2.71828183  7.3890561  20.08553692]
log: [1.38629436 1.60943791 1.79175947]


## 6. 广播（Broadcasting）
不同形状的数组进行算术运算时，NumPy 会自动广播以匹配形状。

In [64]:
# 示例
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 0, 1])
print(a + b)

[[2 2 4]
 [5 5 7]]


## 7. 聚合函数
- `sum`, `mean`, `std`, `var`, `min`, `max`
- axis 参数控制维度

In [71]:

# NumPy 数组
arr = np.arange(1, 7).reshape(2, 3)
print(arr)
print("总和:", arr.sum())
print("按列求和:", arr.sum(axis=0))  # → array([5, 7, 9])，对“列”求和
print("按行求和:", arr.sum(axis=1))  # → array([ 6, 15])，对“行”求和
print("均值:", arr.mean(), "标准差:", arr.std())

# Pandas DataFrame
df = pd.DataFrame(arr, columns=list('ABC'))
print(df)
print(df.sum(axis=0))
print(df.sum(axis=1))

[[1 2 3]
 [4 5 6]]
总和: 21
按列求和: [5 7 9]
按行求和: [ 6 15]
均值: 3.5 标准差: 1.707825127659933
   A  B  C
0  1  2  3
1  4  5  6
A    5
B    7
C    9
dtype: int64
0     6
1    15
dtype: int64


## 8. 重塑与转置
- `reshape`
- `flatten` / `ravel`
- `transpose` / `.T`

In [72]:
# 示例
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
flattened = reshaped.flatten()
transposed = reshaped.T

reshaped, flattened, transposed

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

## 9. 堆叠与拆分
- 水平堆叠：`hstack`, `concatenate`
- 垂直堆叠：`vstack`
- 拆分：`split`, `hsplit`, `vsplit`

In [74]:
# 示例
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
h = np.hstack([a, b])
v = np.vstack([a, b])
splits = np.hsplit(h, 2)

a, b, h, v, splits

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 [array([[0, 1, 2],
         [3, 4, 5]]),
  array([[ 6,  7,  8],
         [ 9, 10, 11]])])

## 10. 线性代数
`np.linalg` 模块：点积、逆、特征值等

In [75]:
# 示例
from numpy.linalg import inv, det, eig, solve

mat = np.array([[3, 1], [2, 4]])
print("逆矩阵:", inv(mat))
print("行列式:", det(mat))
print("特征值与特征向量:", eig(mat))

# 线性方程组
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
print("求解 Ax = b:", solve(A, b))

逆矩阵: [[ 0.4 -0.1]
 [-0.2  0.3]]
行列式: 10.000000000000002
特征值与特征向量: EigResult(eigenvalues=array([2., 5.]), eigenvectors=array([[-0.70710678, -0.4472136 ],
       [ 0.70710678, -0.89442719]]))
求解 Ax = b: [-4.   4.5]


## 11. 随机数生成
`np.random`：种子、分布

In [76]:
# 示例
np.random.seed(42)
print("随机整数:", np.random.randint(0, 10, size=5))
print("标准正态分布:", np.random.randn(5))

随机整数: [6 3 7 4 6]
标准正态分布: [-0.91682684 -0.12414718 -2.01096289 -0.49280342  0.39257975]
